### PR TITLE
Correct some typos

### PR DESCRIPTION
**Pull request by ttwoxa**
A few typos I noticed (:

### CODE REVIEW

**Comment by pavinjosdev** [comment]
@ttwoxa Thank you for the PR 🤗

The `its` change to `it's` is problematic through.
Reference: https://www.grammarly.com/blog/its-vs-its/

Could you fix that?
But otherwise nice job 🎉

**Comment by ttwoxa** [comment]
Ohh i see, thanks for the correction :)

**Comment by ttwoxa** [comment]
After some mistakes by me again it must be okay now.

**Comment by pavinjosdev** [comment]
@ttwoxa  Merged, thank you for making zypperoni better. 🎉🚀

**Pull request merged**
